SHELL = /bin/bash -o pipefail
# https://reactjs.org/
# https://create-react-app.dev/docs/deployment/
.DEFAULT_GOAL := start

start:
	npm start

# homepage field in package.json
build:
	npm run build

test:
	npm run test

serve:
	serve -s build
